# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'AWS.EC2@ubuntu'

variables:
  - group: my_variable_group
  - name: DBuser
    value: $(DBuser)
  - name: password
    value: $(password)
      
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - task: CmdLine@2
            displayName: Build Task
            inputs:
              script: |
                echo "Starting to build the task"
                whoami
                pwd
                echo "10-second delay"
                timeout 10s sleep 10
                echo "Build stage running end now"

  - stage: DEV
    displayName: DEV Stage
    dependsOn: Build
    jobs:
      - job: DEVJob
        displayName: DEV Job
        steps:
          - task: CmdLine@2
            displayName: DEV Task
            inputs:
              script: |
                echo "Starting to DEV the task"
                systemctl start apache2
                systemctl enable apache2
                sudo ufw allow 'Apache'
                echo "DEV stage running end now"

  - stage: PREPROD
    displayName: PREPROD Stage
    dependsOn: DEV
    jobs:
      - job: PREPRODJob
        displayName: PREPROD Job
        steps:
          - task: CmdLine@2
            displayName: PREPROD Task
            inputs:
              script: |
                echo "Starting to PREPROD the task"
                mkdir -p /var/www/html/web1
                sudo cp -R /home/ubuntu/myagent/work_dir/1/s/* /var/www/html/web1/
                sudo chown -R www-data:www-data /var/www/html/web1
                sudo chmod -R 775 /var/www/html/web1
                echo "PREPROD stage running end now"

  - stage: PROD
    displayName: PROD Stage
    dependsOn: PREPROD
    jobs:
      - job: PRODJob
        displayName: PROD Job
        steps:
          - task: CmdLine@2
            displayName: PROD Task
            inputs:
              script: |
                echo "Starting to PROD the task"
                sudo cp -R /home/ubuntu/myagent/work_dir/1/s/web1.conf /etc/apache2/sites-available/
                sudo a2dissite 000-default.conf 
                sudo a2ensite web1.conf
                systemctl reload apache2
                echo "PROD stage running end now"
                echo "Apache web1 up and live. Check this IP http://web1.opsdemo.xyz/"
                echo "Access the website using http://54.205.170.100/"