trigger:
  - master

pool: AWS.EC2@ubuntu

stages:
  - stage: build
    displayName: build stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        pool: AWS.EC2@ubuntu
        steps:
          - task: CmdLine@2
            displayName: build task
            inputs:
              script: |
                echo "starting to build the task"
                whoami
                pwd
                echo "10 second delay"
                timeout 10s sleep 10
                echo " BUILD stage running and end now"

  - stage: DEV
    displayName: DEV stage
    dependsOn: build
    jobs:
      - job: DEVJob
        displayName: DEV Job
        pool: AWS.EC2@ubuntu
        steps:
          - task: CmdLine@2
            displayName: DEV task
            inputs:
              script: |
                systemctl start apache2
                systemctl enable apache2
                sudo ufw allow 'Apache'
                echo " DEV stage running and end now"

  - stage: PREPEROD
    displayName: PREPEROD stage
    dependsOn: DEV
    jobs:
      - job: PREPERODdJob
        displayName: PREPEROD Job
        pool: AWS.EC2@ubuntu
        steps:
          - task: CmdLine@2
            displayName: PREPEROD task
            inputs:
              script: |
                mkdir /var/www/htlm/web1
                sudo cp -R /home/ubuntu/myagent/work_dir/1/s/* /var/www/html/web1/
                sudo chown -R www-data:www-data /var/www/html/web1
                sudo chmod -R 775 /var/www/html/web1
                echo " PREPEROD stage running and end now"

  - stage: PROD
    displayName: PROD stage
    dependsOn: PREPEROD
    jobs:
      - job: PRODJob
        displayName: PROD Job
        pool: AWS.EC2@ubuntu
        steps:
          - task: CmdLine@2
            displayName: PROD task
            inputs:
              script: |
                sudo cp -R /home/ubuntu/myagent/work_dir/1/s/web1.conf /etc/apache2/sites-available/
                sudo a2dissite 000-default.conf 
                sudo a2ensite web1.conf
                systemctl reload apache2
                echo " PROD stage running and end now"
                echo "apache installed and configured check this ip http://web1.opsdemo.xyz/"
                echo "Access the website using http://34.230.65.229/"
