# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: AWS.EC2@ubuntu

stages:
  - stage: build
    displayName: "build stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        pool: AWS.EC2@ubuntu
        steps:
          - task: CmdLine@2
            displayName: "builds"
            inputs:
              script: |
                echo Write your commands here
                
                echo Hello world
              


